import{a as p,S as m,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const y="51454391-664c00f7a8e881ab1c8a3c773",h="https://pixabay.com/api/";async function g(o){const s={key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return p.get(h,{params:s}).then(function(e){return e.data}).catch(function(e){console.log("Error:",e)})}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),L=new m(".gallery a",{captionsData:"alt",captoionDelay:250});function b(o){const s=o.map(e=>` <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"/>
        </a>
        <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",s),L.refresh()}function v(){l.innerHTML=""}function w(){u.classList.add("is-visible")}function q(){u.classList.remove("is-visible")}const d=document.querySelector(".form"),i=d.elements["search-text"];d.addEventListener("submit",async o=>{o.preventDefault();const s=i.value.trim();if(!s){a.warning({message:"Please enter a search query!",position:"topRight"});return}w(),v();try{const e=await g(s);if(e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(e.hits)}catch{a.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{q(),i.value="",i.classList.remove("pressed")}});const f=document.querySelector(".input-form");f.addEventListener("focus",()=>{i.classList.add("pressed")});f.addEventListener("blur",()=>{i.value.trim()===""&&i.classList.remove("pressed")});
//# sourceMappingURL=index.js.map
